#!/usr/bin/env python3
"""
build_content.py — compile the editable content into what the site engine loads.

The CMS (and hand-editors) write one Markdown file per photograph in
content/photos/<id>.md: YAML frontmatter (image, caption, lat, lon, bearing, fov,
taken_at, sources) plus the narrative as the Markdown body. This script turns
that source of truth into the files the static engine consumes:

  content/photos/<id>.md   →   js/data/photos.js          (the photoInfo array)
                           →   narratives/<image-base>.md  (the narrative)
                           →   photos/web/<image>, photos/thumb/<image>  (tiers)

Any of lat / lon / bearing / fov / taken_at left blank in the frontmatter are
filled from the photograph's EXIF (GPS position, GPSImgDirection, and the field
of view computed from the 35mm-equivalent focal length) — the same logic as
add_photo.py and make_thumbs.py, kept self-contained here so CI needs nothing
but Pillow + PyYAML.

Run locally:  python3 scripts/build_content.py
In CI:        .github/workflows/build-content.yml runs it on every content change.

js/data/photos.js and narratives/*.md are GENERATED by this script. Edit photos
through /admin or by editing content/photos/<id>.md, not the generated files.

Requires:  pip3 install Pillow PyYAML
"""

import os, sys, re, glob, json, math
import yaml
from PIL import Image, ImageOps
from PIL.ExifTags import TAGS, GPSTAGS

REPO        = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONTENT_DIR = os.path.join(REPO, "content", "photos")
PHOTOS_DIR  = os.path.join(REPO, "photos")
PHOTOS_JS   = os.path.join(REPO, "js", "data", "photos.js")
NARR_DIR    = os.path.join(REPO, "narratives")
TIERS       = [("thumb", 480, 80), ("web", 1400, 82)]

HEADER = (
    "/* ============================================================================\n"
    "   photos.js — GENERATED FILE. Do not edit by hand.\n"
    "   Built from content/photos/*.md by scripts/build_content.py (and in CI by\n"
    "   .github/workflows/build-content.yml). Edit photographs through /admin or by\n"
    "   editing content/photos/<id>.md; this file is overwritten on the next build.\n"
    "   ============================================================================ */\n"
)

# ── EXIF helpers (mirror add_photo.py) ──────────────────────────────────────
def _dms_to_dec(dms, ref):
    d, m, s = [float(x) for x in dms]
    v = d + m / 60 + s / 3600
    return round(-v if ref in ("S", "W") else v, 6)

def read_exif(path):
    """Return dict with any of lat, lon, bearing, fov, taken_at found in EXIF."""
    out = {}
    try:
        im = Image.open(path)
        w, h = im.size
        exif = im._getexif() or {}
    except Exception:
        return out
    named = {TAGS.get(k, k): v for k, v in exif.items()}
    if named.get("DateTimeOriginal"):
        out["taken_at"] = named["DateTimeOriginal"]
    gps = {}
    if named.get("GPSInfo"):
        gps = {GPSTAGS.get(k, k): v for k, v in named["GPSInfo"].items()}
    if "GPSLatitude" in gps and "GPSLongitude" in gps:
        out["lat"] = _dms_to_dec(gps["GPSLatitude"], gps.get("GPSLatitudeRef", "N"))
        out["lon"] = _dms_to_dec(gps["GPSLongitude"], gps.get("GPSLongitudeRef", "E"))
    if "GPSImgDirection" in gps:
        try:
            out["bearing"] = round(float(gps["GPSImgDirection"]), 1)
        except Exception:
            pass
    focal35 = named.get("FocalLengthIn35mmFilm") or named.get("FocalLenIn35mmFilm")
    if focal35:
        # Horizontal field of view from the 35mm-equivalent focal length.
        # Long sensor side = 36mm (landscape); for a portrait frame use 24mm.
        long_side = 36.0 if w >= h else 24.0
        out["fov"] = round(math.degrees(2 * math.atan(long_side / (2 * float(focal35)))), 1)
    return out

# ── Frontmatter parsing ─────────────────────────────────────────────────────
def parse_md(text):
    m = re.match(r"^---\s*\n(.*?)\n---\s*\n?(.*)\Z", text, re.S)
    if not m:
        return {}, text.strip()
    fm = yaml.safe_load(m.group(1)) or {}
    return fm, m.group(2).strip()

def image_basename(fm):
    img = (fm.get("image") or "").strip()
    return os.path.basename(img) if img else ""

# ── photos.js emitter (readable, one entry per block) ───────────────────────
def emit_photos_js(entries):
    blocks = []
    for e in entries:
        lines = ['    "file": ' + json.dumps(e["file"]),
                 '    "lat": ' + json.dumps(e["lat"]),
                 '    "lon": ' + json.dumps(e["lon"]),
                 '    "caption": ' + json.dumps(e.get("caption", ""), ensure_ascii=False),
                 '    "source_ids": ' + json.dumps(e.get("source_ids", []), ensure_ascii=False)]
        if e.get("bearing") is not None:
            lines.append('    "bearing": ' + json.dumps(e["bearing"]))
        if e.get("fov") is not None:
            lines.append('    "fov": ' + json.dumps(e["fov"]))
        if e.get("taken_at"):
            lines.append('    "taken_at": ' + json.dumps(e["taken_at"]))
        blocks.append("  {\n" + ",\n".join(lines) + "\n  }")
    return HEADER + "const photoInfo = [\n" + ",\n".join(blocks) + "\n];\n"

# ── Tier generation (mirror make_thumbs.py) ─────────────────────────────────
def ensure_tiers(filename):
    src = os.path.join(PHOTOS_DIR, filename)
    if not os.path.exists(src):
        return
    needed = [(n, mx, q) for (n, mx, q) in TIERS
              if not os.path.exists(os.path.join(PHOTOS_DIR, n, filename))]
    if not needed:
        return
    img = ImageOps.exif_transpose(Image.open(src)).convert("RGB")
    for name, maxdim, q in needed:
        os.makedirs(os.path.join(PHOTOS_DIR, name), exist_ok=True)
        d = img.copy()
        d.thumbnail((maxdim, maxdim), Image.LANCZOS)
        d.save(os.path.join(PHOTOS_DIR, name, filename), "JPEG",
               quality=q, optimize=True, progressive=True)
        print(f"  tier  photos/{name}/{filename}")

# ── Main ────────────────────────────────────────────────────────────────────
def main():
    if not os.path.isdir(CONTENT_DIR):
        print(f"No {CONTENT_DIR} — nothing to build (the template's hand-edited "
              f"photos.js is left untouched).")
        return

    files = sorted(glob.glob(os.path.join(CONTENT_DIR, "*.md")))
    entries = []
    keep_narratives = set()

    for f in files:
        fm, body = parse_md(open(f, encoding="utf-8").read())
        filename = image_basename(fm)
        if not filename:
            print(f"  skip (no image): {os.path.basename(f)}")
            continue

        exif = read_exif(os.path.join(PHOTOS_DIR, filename))
        def pick(key):
            v = fm.get(key)
            return v if v not in (None, "") else exif.get(key)

        entry = {
            "file": filename,
            "lat": pick("lat"),
            "lon": pick("lon"),
            "caption": fm.get("caption") or "",
            "source_ids": fm.get("sources") or [],
            "bearing": pick("bearing"),
            "fov": pick("fov"),
            "taken_at": pick("taken_at"),
        }
        if entry["lat"] is None or entry["lon"] is None:
            print(f"  WARNING: no coordinates for {filename} "
                  f"(no lat/lon in frontmatter and none in EXIF). Skipping.")
            continue
        entries.append(entry)
        ensure_tiers(filename)

        base = os.path.splitext(filename)[0]
        narr_path = os.path.join(NARR_DIR, base + ".md")
        if body:
            with open(narr_path, "w", encoding="utf-8") as nf:
                nf.write(body.rstrip() + "\n")
            keep_narratives.add(base)
            print(f"  narrative  narratives/{base}.md")

    # Remove narratives whose photo no longer has body text (cleared in the CMS).
    have = {os.path.splitext(image_basename(parse_md(open(f, encoding='utf-8').read())[0]))[0]
            for f in files}
    for base in have:
        if not base:
            continue
        p = os.path.join(NARR_DIR, base + ".md")
        if base not in keep_narratives and os.path.exists(p):
            os.remove(p)
            print(f"  removed narratives/{base}.md (empty narrative)")

    with open(PHOTOS_JS, "w", encoding="utf-8") as out:
        out.write(emit_photos_js(entries))
    print(f"\nWrote js/data/photos.js with {len(entries)} photograph(s).")


if __name__ == "__main__":
    main()
