#!/usr/bin/env python3
"""
migrate_to_content.py — one-time: turn js/data/photos.js + narratives/*.md into
the editable content/photos/<id>.md source files the CMS uses.

Run this once when enabling the CMS. After it, content/photos/*.md is the source
of truth and js/data/photos.js is generated by build_content.py. Safe to re-run
(it overwrites the content files from the current photos.js).

Requires:  pip3 install PyYAML
"""

import os, re, json, yaml

REPO        = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PHOTOS_JS   = os.path.join(REPO, "js", "data", "photos.js")
NARR_DIR    = os.path.join(REPO, "narratives")
CONTENT_DIR = os.path.join(REPO, "content", "photos")


# Quote every string scalar, so captions/timestamps with YAML-special characters
# (colons, leading brackets, etc.) are unambiguous to both PyYAML and Decap's
# js-yaml. Numbers (lat/lon/bearing/fov) stay unquoted.
def _quote_strings(dumper, data):
    return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="'")
yaml.add_representer(str, _quote_strings, Dumper=yaml.SafeDumper)


def load_photos_js():
    text = open(PHOTOS_JS, encoding="utf-8").read()
    s, e = text.find("["), text.rfind("]")
    return json.loads(text[s:e + 1]) if s >= 0 and e >= 0 else []


def main():
    os.makedirs(CONTENT_DIR, exist_ok=True)
    photos = load_photos_js()
    for p in photos:
        base = os.path.splitext(p["file"])[0]
        narr_path = os.path.join(NARR_DIR, base + ".md")
        body = open(narr_path, encoding="utf-8").read().strip() if os.path.exists(narr_path) else ""

        fm = {"image": "/photos/" + p["file"], "caption": p.get("caption", "")}
        for k in ("lat", "lon", "bearing", "fov", "taken_at"):
            if p.get(k) is not None:
                fm[k] = p[k]
        if p.get("source_ids"):
            fm["sources"] = p["source_ids"]

        front = yaml.safe_dump(fm, sort_keys=False, allow_unicode=True, default_flow_style=False)
        out = os.path.join(CONTENT_DIR, base + ".md")
        with open(out, "w", encoding="utf-8") as f:
            f.write("---\n" + front + "---\n\n" + (body + "\n" if body else ""))
        print(f"  wrote content/photos/{base}.md" + ("  (+narrative)" if body else ""))

    print(f"\nMigrated {len(photos)} photograph(s) to content/photos/.")


if __name__ == "__main__":
    main()
